info.app.name=Admissions Document Management API
server.servlet.context-path=/fndocmgmt
server.port = 8092
genus.application.id=filenet-docmgmt

# Various logging for debugging

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.springframework.orm.jpa=DEBUG
#logging.level.org.springframework.transaction=DEBUG

#logging.level.org.springframework.security=DEBUG

dkgeneric.pdflib.type=itext7
genus.kafka.producer_mapping=true
genus.kafka.producer=true