spring.profiles.active=dev
# enable producer service for reprocessing
dva.ecm.kafka.producer=
# do not use kafka audit rom p8-commons-lib
#dva.ecm.kafka.consumer.useKafkaAudit=false
info.app.name=Admissions Document Management API
server.servlet.context-path=/docs/api/v1
server.port = 8092

dva.ecm.application.id=ecm-docmgmt

# Various logging for debugging

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.springframework.orm.jpa=DEBUG
#logging.level.org.springframework.transaction=DEBUG

#logging.level.org.springframework.security=DEBUG
dva.ecm.pdflib.type=itext7
