info.app.name=Admissions Document Management API
server.servlet.context-path=/docs/api/v1
server.port = 8092
server.error.include-message=always

# to avoid protocol switch on vip configured https->http
server.forward-headers-strategy = framework

spring.servlet.multipart.max-file-size = 100MB
spring.servlet.multipart.max-request-size = 100MB

management.endpoints.web.exposure.include= metrics,health
management.endpoint.health.show-details=always

jasypt.encryptor.password=${JASYPT_PASSWORD}

dva.ecm.application.id=ecm-docmgmt

# taxonomy data source
com.davita.jpa.taxonomycfg.datasource.driver-class-name=oracle.jdbc.OracleDriver
com.davita.jpa.taxonomycfg.datasource.jdbcUrl=jdbc:oracle:thin:@sea1l3p8dbd01.davita.corp:1533:ECMDEV2
com.davita.jpa.taxonomycfg.datasource.username=svc_ecm_appconfig_np
com.davita.jpa.taxonomycfg.datasource.password=ENC(Mb+uA1GF6y1UH9Te4KOZrg3bvvFZFIensHRPzFt1lfA=)

dva.ecm.authentication.none=true

# Various logging for debugging

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.springframework.orm.jpa=DEBUG
#logging.level.org.springframework.transaction=DEBUG

#logging.level.org.springframework.security=DEBUG

spring.jpa.hibernate.hikari.minimumIdle=3
spring.datasource.hikari.maximum-pool-size=8